//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KutuphaneDBEntitiesLast : DbContext
    {
        public KutuphaneDBEntitiesLast()
            : base("name=KutuphaneDBEntitiesLast")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLCezalar> TBLCezalar { get; set; }
        public virtual DbSet<TBLHareketler> TBLHareketler { get; set; }
        public virtual DbSet<TBLKasa> TBLKasa { get; set; }
        public virtual DbSet<TBLKategory> TBLKategory { get; set; }
        public virtual DbSet<TBLKitap> TBLKitap { get; set; }
        public virtual DbSet<TBLPersonel> TBLPersonel { get; set; }
        public virtual DbSet<TBLUyeler> TBLUyeler { get; set; }
        public virtual DbSet<TBLYazarlar> TBLYazarlar { get; set; }
    }
}
