//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKitap()
        {
            this.TBLHareketler = new HashSet<TBLHareketler>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public Nullable<byte> Kategory { get; set; }
        public Nullable<int> Yazar { get; set; }
        public string Basimyill { get; set; }
        public string Yayınevi { get; set; }
        public string Sayfa { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHareketler> TBLHareketler { get; set; }
        public virtual TBLKategory TBLKategory { get; set; }
        public virtual TBLYazarlar TBLYazarlar { get; set; }
    }
}
